### ISSUE TITLE
Is this still active?

### ISSUE THREAD

**Issue by athendwyl** [ryanayoung/projectSpigot#1]
Asking because it hasn't been updated in nearly a year. If it's not, then please archive it and indicate the status in the 'readme' file.

**Comment by ericmoderbacher** [comment]
Not necessarily inactive. I don't think we answer to you.

**Comment by athendwyl** [comment]
My apologies, it was not my intention to impose. I was simply making a request, although, going through and reading my request, I can see that it does kind of resemble a very firm request from a community or forum admin. Sorry about that.
